version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: container_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: localpg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres

volumes:
  postgres_data:
